def printSkull():
    """ function to print skull when you are die """
    center_int = 64
    print(('.ed""""."""$$$be.  ').center(center_int))
    print((' ="'+' '*11+'_""**$$$e.  ').center(center_int))
    print((' ."'+' '*19+'\'$$$c  ').center(center_int))
    print(('/'+' '*22+'"4$$b  ').center(center_int))
    print(('d  3'+' '*21+'$$$$  ').center(center_int))
    print(('$  *'+' '*19+'.$$$$$$  ').center(center_int))
    print(('.$  -c'+' '*11+'$'*5+'e'+'$'*8+'.  ').center(center_int))
    print(('d$L  4.'+' '*9+'4'+'$'*14+'b  ').center(center_int))
    print(('$$$$b -ceeeee.  4$$ECL.F*'+'$'*7+'  ').center(center_int))
    print(('e$""-.      $$$$P d$$$$F $ '+'$'*9+'- '+'$'*6+'             ').center(center_int))
    print(('z$$b. -c     3$$$F "$$$$b   $"'+'$'*7+'  '+'$'*4+'*"      .=""$c  ').center(center_int))
    print(('4$$$$L   %     $$P"  "$$b   .$ '+'$'*5+'  '+'$'*4+'*"     .=   e$$$.  ').center(center_int))
    print(('-*$$$$$c  %..   *c    ..    $$ 3'+'$'*10+'eF     zP  d$$$$$  ').center(center_int))
    print(('"**$$$ec   "%   ?ce""    $$$  '+'$'*10+'*    .r" =$$$$P"" ').center(center_int))
    print(('   "*$b.  "c  *$e.    *** d'+'$'*5+'"L$$    .d"  e$$***"').center(center_int))
    print(('_*$$c -$c $$$      4J'+'$'*5+'% $$$ .e*".eeP"').center(center_int))
    print((' "'+'$'*6+'"\'$=e    $*$$**$cz$$" "..d$*"').center(center_int))
    print(('"*$$$  *=%4.$ L L$ P3$$$F $$$P"').center(center_int))
    print(('"$   "%*ebJLzb$e$$$$$b $P"').center(center_int))
    print(('%..      4'+'$'*10+' "').center(center_int))
    print(('$$$e   z'+'$'*10+'%').center(center_int))
    print(('"*$c  "'+'$'*7+'P"  ').center(center_int))
    print(('."""*'+'$'*8+'bc').center(center_int))
    print(('.-"'+' '*5+'.$***$$$"""*e.  ').center(center_int))
    print(('.-"'+' '*4+'.e$"'+' '*6+'"*$c  -*b.   ').center(center_int))
    print(('.=*"""""'+' '*4+'.e$*"'+' '*11+'"*bc  "*$e..      ').center(center_int))
    print(('.$"'+' '*9+'.z*"'+' '*16+'_*$e.   "*****e.  ').center(center_int))
    print((' $$ee$c   .d"'+' '*23+'"*$.        3.  ').center(center_int))
    print((' _*$E")$  $"'+' '*27+'*   .ee==d%  ').center(center_int))
    print(('  $.d$$$*'+' '*29+'*  J$$$e*').center(center_int))
    print(('"""""'+' '*31+'"$$$"').center(center_int))
